name: pages-build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * *' # Runs every day at 6am

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub pages build endpoint
        run: |
          curl -L --fail --request POST \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --url https://api.github.com/repos/fwinkl/fwinkl.github.io/pages/builds

        env:
          # Create a token at https://github.com/settings/tokens
          # since you cannot trigger a new build with the regular token.
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
