name: pages-build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 1' # Monday 4am

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub pages build endpoint
        run: |
          curl -L --fail --request POST \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer $USER_TOKEN" \
            --url https://api.github.com/repos/fwinkl/fwinkl.github.io/pages/builds
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
